#!/usr/bin/env python3
"""
gen_bridge_config.py — generates src/titan_coordination/config/bridge.yaml
for the full 5-robot fleet (leader + follower_1..4).

Every robot's plugins/sensors publish on explicitly namespaced gz topics
(e.g. "/leader/scan", "/follower_2/imu/data" — see husky_leader/model.sdf
and follower_N/model.sdf for why the namespace has to be baked into each
<topic> rather than relying on gz-sim's per-instance auto-scoping). Those
gz topic strings are already valid ROS topic names, so most bridge entries
are a straight passthrough (topic_name: same string both sides) — only the
GPS entry renames gz's "navsat" to ROS's conventional "gps/fix", same as
the original single-robot bridge.yaml.

Usage:
    python3 scripts/gen_bridge_config.py
"""

import os

WS_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT_PATH = os.path.join(WS_ROOT, "src", "titan_coordination", "config", "bridge.yaml")

FLEET = ["leader", "follower_1", "follower_2", "follower_3", "follower_4"]

HEADER = """# ros_gz_bridge topic mapping configuration — AUTO-GENERATED by
# scripts/gen_bridge_config.py. Do not hand-edit — regenerate instead so
# all 5 robots stay consistent. See that script's docstring for why the
# per-robot topics are a straight passthrough except GPS.
#
# Docs: https://github.com/gazebosim/ros_gz/tree/ros2/ros_gz_bridge
# direction: GZ_TO_ROS = sensor data flowing out of Gazebo
#            ROS_TO_GZ = commands flowing into Gazebo

# ── Clock ──
# Syncs ROS 2 time with Gazebo sim time. Every node needs use_sim_time:=true.
- topic_name: "/clock"
  ros_type_name: "rosgraph_msgs/msg/Clock"
  gz_type_name: "gz.msgs.Clock"
  direction: GZ_TO_ROS
"""

PASSTHROUGH_ENTRIES = [
    # (suffix, ros_type_name, gz_type_name, direction, comment)
    ("cmd_vel", "geometry_msgs/msg/Twist", "gz.msgs.Twist", "ROS_TO_GZ",
     "Drive commands: FISVFH/teleop/follower controller -> DiffDrive plugin."),
    ("odom", "nav_msgs/msg/Odometry", "gz.msgs.Odometry", "GZ_TO_ROS",
     "Wheel odometry from DiffDrive plugin -> EKF odom0 input."),
    ("joint_states", "sensor_msgs/msg/JointState", "gz.msgs.Model", "GZ_TO_ROS",
     "Wheel joint states, for completeness / future robot_state_publisher use."),
    ("imu/data", "sensor_msgs/msg/Imu", "gz.msgs.IMU", "GZ_TO_ROS",
     "IMU -> EKF imu0 input."),
    ("scan", "sensor_msgs/msg/LaserScan", "gz.msgs.LaserScan", "GZ_TO_ROS",
     "2D lidar -> FISVFH obstacle histogram."),
    ("camera/image", "sensor_msgs/msg/Image", "gz.msgs.Image", "GZ_TO_ROS",
     "Camera -> fiducial tracking (Week 7-8)."),
]


def render_robot_block(ns: str) -> str:
    lines = [f"\n# ══════════════ {ns} ══════════════"]
    for suffix, ros_type, gz_type, direction, comment in PASSTHROUGH_ENTRIES:
        lines.append(f"# {comment}")
        lines.append(f'- topic_name: "/{ns}/{suffix}"')
        lines.append(f'  ros_type_name: "{ros_type}"')
        lines.append(f'  gz_type_name: "{gz_type}"')
        lines.append(f"  direction: {direction}")
    # GPS: gz-side "navsat" -> ROS-side "gps/fix" (names differ, so split explicitly
    # — a single topic_name here would apply "gps/fix" to both sides and the bridge
    # would subscribe to a gz topic nothing publishes on).
    lines.append("# GPS: gz-side topic name differs from the ROS convention.")
    lines.append(f'- ros_topic_name: "/{ns}/gps/fix"')
    lines.append(f'  gz_topic_name: "/{ns}/navsat"')
    lines.append('  ros_type_name: "sensor_msgs/msg/NavSatFix"')
    lines.append('  gz_type_name: "gz.msgs.NavSat"')
    lines.append("  direction: GZ_TO_ROS")
    return "\n".join(lines) + "\n"


def main():
    content = HEADER + "".join(render_robot_block(ns) for ns in FLEET)
    with open(OUT_PATH, "w") as f:
        f.write(content)
    print(f"wrote {OUT_PATH}")


if __name__ == "__main__":
    main()
