#!/usr/bin/env python3
"""
gen_follower_models.py — generates models/<namespace>/model.sdf + model.config
for each Jackal-sized follower robot.

Why generated instead of hand-written like husky_leader: the gz-sim-diff-drive
plugin (and the sensor plugins) use each <topic> LITERALLY — an explicit topic
does NOT get namespaced under /model/<include-name>/ (verified with `gz topic
-l` while spawning two named instances of the same model — see the note in
husky_leader/model.sdf). So four followers sharing one static model.sdf would
all fight over the same /cmd_vel, /scan, etc. Each follower needs its own file
with its own namespace baked into every <topic>. Keeping that namespace
substitution in one script (rather than four hand-edited copies) is what keeps
the four files from drifting out of sync.

Usage:
    python3 scripts/gen_follower_models.py

Regenerate after changing FOLLOWER_NAMESPACES or the dimensions below.
"""

import os

WS_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MODELS_DIR = os.path.join(WS_ROOT, "models")

FOLLOWER_NAMESPACES = ["follower_1", "follower_2", "follower_3", "follower_4"]

# Jackal-ish dimensions (Clearpath Jackal is ~0.508 x 0.430 x 0.184 m, ~17 kg).
# Not a precise physical model — same level of rigor as husky_leader/model.sdf,
# just enough for stable physics and a footprint smaller than the leader's.
CHASSIS_L, CHASSIS_W, CHASSIS_H = 0.508, 0.430, 0.184
CHASSIS_MASS = 17.0
WHEEL_RADIUS, WHEEL_WIDTH, WHEEL_MASS = 0.098, 0.040, 0.7
WHEEL_X = 0.131       # half wheelbase (front-rear)
WHEEL_Y = 0.1875      # half track (left-right)
WHEEL_Z = -CHASSIS_H / 2
LIDAR_Z = CHASSIS_H / 2 + 0.10
CAMERA_X = CHASSIS_L / 2 - 0.04
CAMERA_Z = 0.02

# Chassis box inertia: I_xx = m/12 * (y^2 + z^2), etc. — same formula husky_leader uses.
IXX = CHASSIS_MASS / 12 * (CHASSIS_W ** 2 + CHASSIS_H ** 2)
IYY = CHASSIS_MASS / 12 * (CHASSIS_L ** 2 + CHASSIS_H ** 2)
IZZ = CHASSIS_MASS / 12 * (CHASSIS_L ** 2 + CHASSIS_W ** 2)

MODEL_CONFIG_TEMPLATE = """<?xml version="1.0"?>
<model>
  <name>{ns}</name>
  <version>1.0</version>
  <sdf version="1.9">model.sdf</sdf>
  <description>
    Auto-generated by scripts/gen_follower_models.py. Do not hand-edit —
    regenerate instead so the four followers stay consistent.
  </description>
</model>
"""

MODEL_SDF_TEMPLATE = """<?xml version="1.0"?>
<!--
  AUTO-GENERATED by scripts/gen_follower_models.py — do not hand-edit.
  Jackal-sized follower robot. Namespace: "{ns}". Every plugin/sensor
  <topic> below is prefixed "{ns}/" — see husky_leader/model.sdf for why
  that prefix has to be literal instead of relying on gz-sim's per-instance
  auto-scoping (only DiffDrive/JointStatePublisher get the short scoped
  form for free; sensors don't, so we set it explicitly everywhere for
  consistency and to keep bridge.yaml simple and world-independent).
-->
<sdf version="1.9">
  <model name="{ns}">
    <static>false</static>

    <link name="base_link">
      <inertial>
        <mass>{chassis_mass}</mass>
        <inertia>
          <ixx>{ixx:.4f}</ixx>
          <iyy>{iyy:.4f}</iyy>
          <izz>{izz:.4f}</izz>
          <ixy>0</ixy><ixz>0</ixz><iyz>0</iyz>
        </inertia>
      </inertial>

      <collision name="chassis_collision">
        <geometry><box><size>{chassis_l} {chassis_w} {chassis_h}</size></box></geometry>
      </collision>

      <visual name="chassis_visual">
        <geometry><box><size>{chassis_l} {chassis_w} {chassis_h}</size></box></geometry>
        <material>
          <ambient>0.85 0.55 0.05 1</ambient>
          <diffuse>0.95 0.6 0.05 1</diffuse>  <!-- Jackal yellow, to visually tell followers from the leader -->
        </material>
      </visual>

      <sensor name="imu_sensor" type="imu">
        <always_on>true</always_on>
        <update_rate>100</update_rate>
        <topic>{ns}/imu/data</topic>
        <imu>
          <angular_velocity>
            <x><noise type="gaussian"><mean>0</mean><stddev>0.001</stddev></noise></x>
            <y><noise type="gaussian"><mean>0</mean><stddev>0.001</stddev></noise></y>
            <z><noise type="gaussian"><mean>0</mean><stddev>0.001</stddev></noise></z>
          </angular_velocity>
          <linear_acceleration>
            <x><noise type="gaussian"><mean>0</mean><stddev>0.01</stddev></noise></x>
            <y><noise type="gaussian"><mean>0</mean><stddev>0.01</stddev></noise></y>
            <z><noise type="gaussian"><mean>0</mean><stddev>0.01</stddev></noise></z>
          </linear_acceleration>
        </imu>
      </sensor>

      <sensor name="navsat_sensor" type="navsat">
        <always_on>true</always_on>
        <update_rate>5</update_rate>
        <topic>{ns}/navsat</topic>
        <navsat>
          <position_sensing>
            <horizontal>
              <noise type="gaussian"><mean>0</mean><stddev>0.0000045</stddev></noise>
            </horizontal>
            <vertical>
              <noise type="gaussian"><mean>0</mean><stddev>1.0</stddev></noise>
            </vertical>
          </position_sensing>
        </navsat>
      </sensor>
    </link>

    <link name="lidar_link">
      <pose relative_to="base_link">0 0 {lidar_z:.3f} 0 0 0</pose>
      <inertial>
        <mass>0.3</mass>
        <inertia><ixx>0.0005</ixx><iyy>0.0005</iyy><izz>0.0005</izz><ixy>0</ixy><ixz>0</ixz><iyz>0</iyz></inertia>
      </inertial>
      <collision name="lidar_collision">
        <geometry><cylinder><radius>0.04</radius><length>0.04</length></cylinder></geometry>
      </collision>
      <visual name="lidar_visual">
        <geometry><cylinder><radius>0.04</radius><length>0.04</length></cylinder></geometry>
        <material><ambient>0.0 0.0 0.8 1</ambient><diffuse>0.0 0.0 0.8 1</diffuse></material>
      </visual>
      <sensor name="lidar_sensor" type="gpu_lidar">
        <always_on>true</always_on>
        <update_rate>10</update_rate>
        <topic>{ns}/scan</topic>
        <lidar>
          <scan>
            <horizontal>
              <samples>360</samples>
              <resolution>1</resolution>
              <min_angle>-3.14159</min_angle>
              <max_angle>3.14159</max_angle>
            </horizontal>
          </scan>
          <range><min>0.15</min><max>30.0</max><resolution>0.01</resolution></range>
          <noise><type>gaussian</type><mean>0</mean><stddev>0.01</stddev></noise>
        </lidar>
      </sensor>
    </link>
    <joint name="lidar_joint" type="fixed">
      <parent>base_link</parent>
      <child>lidar_link</child>
    </joint>

    <!--
      Camera faces forward — the follower directly behind this one (or the
      BS during Task 3+) never needs it, but this robot needs to see
      whatever fiducial pose is being tracked ahead of it (Task 4+).
    -->
    <link name="camera_link">
      <pose relative_to="base_link">{camera_x:.3f} 0 {camera_z:.3f} 0 0 0</pose>
      <inertial>
        <mass>0.15</mass>
        <inertia><ixx>0.0001</ixx><iyy>0.0001</iyy><izz>0.0001</izz><ixy>0</ixy><ixz>0</ixz><iyz>0</iyz></inertia>
      </inertial>
      <collision name="camera_collision">
        <geometry><box><size>0.03 0.06 0.03</size></box></geometry>
      </collision>
      <visual name="camera_visual">
        <geometry><box><size>0.03 0.06 0.03</size></box></geometry>
        <material><ambient>0.8 0.0 0.0 1</ambient><diffuse>0.8 0.0 0.0 1</diffuse></material>
      </visual>
      <sensor name="camera_sensor" type="camera">
        <always_on>true</always_on>
        <update_rate>30</update_rate>
        <topic>{ns}/camera/image</topic>
        <camera>
          <horizontal_fov>1.3962634</horizontal_fov>
          <image><width>640</width><height>480</height><format>R8G8B8</format></image>
          <clip><near>0.1</near><far>100.0</far></clip>
          <noise><type>gaussian</type><mean>0</mean><stddev>0.005</stddev></noise>
        </camera>
      </sensor>
    </link>
    <joint name="camera_joint" type="fixed">
      <parent>base_link</parent>
      <child>camera_link</child>
    </joint>

{wheels}
    <plugin filename="gz-sim-diff-drive-system"
            name="gz::sim::systems::DiffDrive">
      <left_joint>front_left_wheel_joint</left_joint>
      <left_joint>rear_left_wheel_joint</left_joint>
      <right_joint>front_right_wheel_joint</right_joint>
      <right_joint>rear_right_wheel_joint</right_joint>
      <wheel_separation>{wheel_sep:.3f}</wheel_separation>
      <wheel_radius>{wheel_radius}</wheel_radius>
      <max_linear_acceleration>1.0</max_linear_acceleration>
      <max_angular_acceleration>2.0</max_angular_acceleration>
      <max_linear_velocity>2.0</max_linear_velocity>
      <min_linear_velocity>-2.0</min_linear_velocity>
      <max_angular_velocity>2.0</max_angular_velocity>
      <min_angular_velocity>-2.0</min_angular_velocity>
      <topic>{ns}/cmd_vel</topic>
      <odom_topic>{ns}/odom</odom_topic>
      <tf_topic>{ns}/tf</tf_topic>
      <odom_publish_frequency>50</odom_publish_frequency>
    </plugin>

    <plugin filename="gz-sim-joint-state-publisher-system"
            name="gz::sim::systems::JointStatePublisher">
      <topic>{ns}/joint_states</topic>
    </plugin>

  </model>
</sdf>
"""

WHEEL_TEMPLATE = """    <link name="{wheel_name}_wheel">
      <pose relative_to="base_link">{x:.3f} {y:.3f} {z:.3f} -1.5708 0 0</pose>
      <inertial>
        <mass>{wheel_mass}</mass>
        <inertia><ixx>0.002</ixx><iyy>0.002</iyy><izz>0.001</izz><ixy>0</ixy><ixz>0</ixz><iyz>0</iyz></inertia>
      </inertial>
      <collision name="collision">
        <geometry><cylinder><radius>{wheel_radius}</radius><length>{wheel_width}</length></cylinder></geometry>
        <surface>
          <friction><ode><mu>1.0</mu><mu2>0.5</mu2></ode></friction>
          <contact><ode><kp>1e6</kp><kd>500</kd></ode></contact>
        </surface>
      </collision>
      <visual name="visual">
        <geometry><cylinder><radius>{wheel_radius}</radius><length>{wheel_width}</length></cylinder></geometry>
        <material><ambient>0.1 0.1 0.1 1</ambient><diffuse>0.1 0.1 0.1 1</diffuse></material>
      </visual>
    </link>
    <joint name="{wheel_name}_wheel_joint" type="revolute">
      <parent>base_link</parent>
      <child>{wheel_name}_wheel</child>
      <axis><xyz>0 0 1</xyz><limit><lower>-1e16</lower><upper>1e16</upper></limit></axis>
    </joint>
"""


def render_wheels():
    wheels = [
        ("front_left", WHEEL_X, WHEEL_Y),
        ("front_right", WHEEL_X, -WHEEL_Y),
        ("rear_left", -WHEEL_X, WHEEL_Y),
        ("rear_right", -WHEEL_X, -WHEEL_Y),
    ]
    return "\n".join(
        WHEEL_TEMPLATE.format(
            wheel_name=name, x=x, y=y, z=WHEEL_Z,
            wheel_mass=WHEEL_MASS, wheel_radius=WHEEL_RADIUS, wheel_width=WHEEL_WIDTH,
        )
        for name, x, y in wheels
    )


def main():
    wheels_xml = render_wheels()
    for ns in FOLLOWER_NAMESPACES:
        model_dir = os.path.join(MODELS_DIR, ns)
        os.makedirs(model_dir, exist_ok=True)

        sdf = MODEL_SDF_TEMPLATE.format(
            ns=ns,
            chassis_mass=CHASSIS_MASS,
            ixx=IXX, iyy=IYY, izz=IZZ,
            chassis_l=CHASSIS_L, chassis_w=CHASSIS_W, chassis_h=CHASSIS_H,
            lidar_z=LIDAR_Z, camera_x=CAMERA_X, camera_z=CAMERA_Z,
            wheels=wheels_xml,
            wheel_sep=2 * WHEEL_Y, wheel_radius=WHEEL_RADIUS,
        )
        with open(os.path.join(model_dir, "model.sdf"), "w") as f:
            f.write(sdf)

        with open(os.path.join(model_dir, "model.config"), "w") as f:
            f.write(MODEL_CONFIG_TEMPLATE.format(ns=ns))

        print(f"wrote {model_dir}/model.sdf + model.config")


if __name__ == "__main__":
    main()
